/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flpCrowndsalceSol from "./FLPCrowndsalce.sol";
export type { flpCrowndsalceSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { Floppy } from "./Floppy";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
